### PR TITLE
chore(tests): replaced jest with node:test

### PR DESCRIPTION
**Pull request by floridemai**
Closes https://github.com/fastify/fluent-json-schema/issues/243

Updated all test files to work with `node:test` runner. Everything went smooth with only two notes: certain expected objects needed and addiional `$id: undefined` property and a test where the error type was invalid.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by simoneb** [comment]
@mcollina build is failing on Node 16, I suspect something incompatible with c8 or even node:test. Are we supposed to still support Node 16 with this library?

**Review by gurgunday — COMMENTED** [review]
Please target next and modify this line to test only on 18, 20, 22:

https://github.com/fastify/fluent-json-schema/blob/9e91b2c4cb2effda3b2e3c7f09fa3f3efac12a2e/.github/workflows/ci.yml#L24

**Comment by aboutlo** [comment]
Thank you for this @floridemai 🙌

**Comment by mcollina** [comment]
We can just drop node.js v16

**Review by gurgunday — APPROVED** [review]
lgtm

**Comment by gurgunday** [comment]
> We can just drop node.js v16

I think to keep things organized we should keep CI changes in next too, we'll start merging `next` branches this month or in July anyway for Fastify v5

**Comment by gurgunday** [comment]
Thanks a lot for the PR!

**Pull request merged**
