### PR TITLE
ci: remove eol node versions from unit tests

### PR DESCRIPTION
**Pull request by Fdawgs**
v8.0.0 and v13.0.0 are no longer supported as seen on https://nodejs.org/en/about/releases/

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
FYI, this is a semver-major change.

**Comment by aboutlo** [comment]
if it isn't broken I would keep it

**Comment by Fdawgs** [comment]
Cool no worries then!

**Comment by aboutlo** [comment]
thank you regardless @Fdawgs :)

**Pull request closed without merging**
