### PR TITLE
replace deepmerge with @fastify/deepmerge

### PR DESCRIPTION
**Pull request by Uzlopak**
To verify that PR https://github.com/fastify/deepmerge/pull/5 for deepmerge works accordingly I tested it locally. To not redo the 
implementation again, I created this PR. My assumption is, that the next release of fastify/deepmerge will be 1.1.0. 

As soon as the PR in deepmerge is merged, this code change should become valid.

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Uzlopak** [comment]
I guess this PR was not merged because of the drop in the code coverage. Added unit tests, and got it back to 100%.

Can this be merged now?

**Review by Fdawgs — APPROVED** [review]

**Comment by mcollina** [comment]
It's @aboutlo decision.

**Comment by Uzlopak** [comment]
Improved the test coverage. So combineDeepmerge is now covered 100%.

**Comment by aboutlo** [comment]
Thank you @Uzlopak!

**Pull request merged**
