### PR TITLE
Update CI workflows

### PR DESCRIPTION
**Pull request by Fdawgs**
Hi there!

This pull request is focused on the CI workflow in this repo, enabling dependabot automatic updates of dependencies, and laying the ground work to be able to fix the coveralls badge as highlighted in #28 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by aboutlo** [comment]
@Fdawgs nice one! LGTM

**Review by mcollina — CHANGES_REQUESTED** [review]
I would recommend dropping package-lock.json. 

As for the why: https://github.com/sindresorhus/ama/issues/479.

**Comment by Fdawgs** [comment]
> 
> 
> I would recommend dropping package-lock.json.
> 
> As for the why: [sindresorhus/ama#479](https://github.com/sindresorhus/ama/issues/479).

Thanks @mcollina, I hadn't see this! I've removed the `package-lock.json` file and reverted back to `npm install` in the `ci.yml`

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
