### PR TITLE
Drop support for EOL Nodejs versions

### PR DESCRIPTION
**Pull request by Fdawgs**
- Drops support for Nodejs v8 (EOL 2019-12-31)
- Drops support for Nodejs v10 (EOL 2021-04-30)
- Updated the Dependabot interval from `monthly` to `daily` to be the same as other Fastify repos

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
We should drop Node 8, not pin jest.

**Comment by Fdawgs** [comment]
> We should drop Node 8, not pin jest.

Cool! Will update this PR.
Should Node 10 be dropped as well with it being EOL tomorrow?

**Comment by mcollina** [comment]
Yes I would recommend doing that and release a semver-major change @aboutlo.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
