### PR TITLE
Use standard and @fastify/pre-commit

### PR DESCRIPTION
**Pull request by Uzlopak**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
I'm generically -1 in changing the formatting of some code.

**Comment by aboutlo** [comment]
I have no strong opinion but it's just cosmetic :)

**Comment by Uzlopak** [comment]
@aboutlo 
It would be then in line with all the other repos.

**Review by Eomm — APPROVED** [review]
I'm +1 to ease the maintenance across repos by adopting the same structure.

_We are free to experiment on personal repos tho_

**Review by zrosenbauer — APPROVED** [review]

**Comment by Uzlopak** [comment]
Thx @Eomm

But should we merge it or not. @aboutlo i assume you have the golden ticket regarding the vote of @mcollina 
Can you approve or close this PR please?

**Comment by aboutlo** [comment]
no strong opinion, but given others signalled in favor and  we can standardise towards what other repo do I will merge it

**Pull request merged**
